### ISSUE TITLE
Include instruction data in context

### ISSUE THREAD

**Issue by Dodecahedr0x** [exotic-markets/crayfish#24]
I suggest that instruction data becomes a part of a context rather than an independent structure (c.f. Anchor).

Motivations for this suggestion are:
- Instruction data are often used in contexts (e.g. generate PDA seeds, make some verification related to the context)
- Defining them separately forces you to define them twice in case they're used by the context (e.g. in Anchor you do `#[instruction(some_data: u64)]` AND `fn handler(ctx: Context<MyAccount>, some_data: u64)`)
- Makes everything contained in the `context-macro` rather than spread around.

One way it could look like is:
```rust
#[context]
#[instruction(some_data: u64)]
pub struct HelloWorldContext {}

pub fn hello_world(ctx: HelloWorldContext) -> Result<(), ProgramError> {
    msg!("{}", ctx.ix_data.some_data);
    Ok(())
}
```

This way, it's familiar for Anchor users but provides the properties above.

**Comment by Aursen** [comment]
Yeah I will add it soon
